### PR TITLE
wtforms-ndb merge

### PR DESCRIPTION
**Pull request by xlevus**
I've done some preliminary work on merging wtforms-ndb back into wtforms-appengine. It's mostly just a copy/paste from what's there.

Fixes/Changes:

- Removed dependencies on nose-gae, tests can now be run with `python setup.py test`. Testbed is setup/torndown in gaetest_common TestCase classes. This assumes the SDK is installed and importable. https://pypi.python.org/pypi/appengine-sdk/ makes this easier.
- KeyProperty and RepeatedKeyProperty fields use `key.urlsafe()` to support ancestor instances. This could potentially be a security concern, as the urlsafe string contains the type, namespace, application and ID of the object and it's ancestors. 
- Repeated properties with `choices` now generates to a `SelectMultiple` field.
- Added a `PrefetchedKeyPropertyField` and `PrefetchedRepeatedKeyPropertyField` to build queries in parallel.

### CODE REVIEW

**Comment by mikelambert** [comment]
Sorry to just reply with a single nitpick...ran out of time this afternoon. Will try to get to the meat of the review tonight.

**Comment by mikelambert** [comment]
Thanks for being so prompt in submitting the pull request, much appreciated. Hopefully the nitpicks/bug/questions aren't too much.. :)

**Comment by xlevus** [comment]
I've reverted the erroneous Key->Model change and deleted tests. And I've added some missing tests.

There's still a few issues:

- setting the query property on the Key fields manually can result in multiple evaluations of the query (see appstats example below).
- urlsafe keys could potentially be leaking unwanted information to the user. This could be fixed by hashing the result of `KeyPropertyField._key_value`.  
- The `model_form` converter is butt ugly, and doesn't support structured properties. I've made some changes [here](https://github.com/xlevus/wtforms-ndb/blob/master/wtforms_ndb/ndb.py), but overall I don't like the way the converter works and haven't included it.

Anything else that needs changing is up to you. I'm out of time.

    def double_eval():
        q = MyModel.query()
        # Iterate the query twice. 
        list(q)
        list(q)

2015-12-22-122456_623x338_scrot

**Comment by mikelambert** [comment]
I had one question I sent out (which I can fix up later), but otherwise this looks great (and good point about python25/26/27 support). And thanks again for taking to the time to submit a pull request for your improvements to wtforms-appengine, I'll merge it in now.

**Pull request merged**
